#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LongTech.Techie.Resource", IsApplication=true)]

namespace LongTech.Techie
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int hyper_link = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int splash_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_sessions = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_speakers = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_whats_on = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int splash_logo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int SplashScreen = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int frameLayoutTechie = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int gridLayout1 = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int imageButtonWorkItemJobStatus = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int listViewAvailableWork = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int listViewMyWork = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int textViewWorkItemClientName = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int textViewWorkItemJobDescription = 2131230725;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int availablework_fragment = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int myprofile_fragment = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int mywork_fragment = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int TechieActivity = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int work_item_listview_adapter = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int tab_label_availablework = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int tab_label_myprofile = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int tab_label_mywork = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int TechieTheme = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int TechieTheme_Base = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int TechieTheme_Splash = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
